#################################################
# Application
#################################################

spring.application.name=ATBM

server.port=8080

#################################################
# Database MySQL
#################################################

spring.datasource.url=jdbc:mysql://localhost:3306/atbm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#################################################
# JPA / Hibernate
#################################################

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#################################################
# Thymeleaf
#################################################

spring.thymeleaf.cache=false

spring.thymeleaf.prefix=classpath:/resource/templates/

spring.thymeleaf.suffix=.html

#################################################
# Static Resources
#################################################

spring.web.resources.static-locations=classpath:/resource/static/

#################################################
# Upload PDF
#################################################

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB

spring.servlet.multipart.max-request-size=20MB

#################################################
# Logging
#################################################

logging.level.org.springframework.web=INFO

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE

#################################################
# Session
#################################################

server.servlet.session.timeout=60m

#################################################
# File Storage
#################################################

app.upload.dir=uploads/pdf